### PR TITLE
Allow people to close brief modals by clicking outside them

### PR DESCRIPTION
**Pull request by alpower**
Hey Luke,

Really love the DesignChallenge site - thank you for making this!

One small enhancement I thought would be nice would be to add the ability to click outside an open design brief modal box to close it - quite a common UX practice (in addition to having a close link, which you already have). This is really useful when browsing on bigger screens.

I've added a small bit of code to check where people click, and close modal if they have clicked outside. I've tested it on desktop, and made sure it doesn't interfere with the mobile view or the view if you go direct to a brief. Tested on Chrome, Safari and Firefox.

Unsure how open you are to people contributing (have never contributed to anything before like this!) but thought I'd try and help out.

HTH,
Al

2018-05-14-designchallenge

### CODE REVIEW

**Comment by robb0wen** [comment]
@alpower Hey Al, seems like a really nice addition to me! Thanks for the contribution 👍 

One note though is that as the header also sits outside of the brief, any clicks on the links up there are being intercepted by the handleClickOutsideBrief function. If you click 'Acknowledgements', for example, the click is stopped and the browser history goes back instead. I feel like those links should probably still be functional from within the brief modal view.

Would you be able to modify the code to only register clicks within the overlay div, but outside of the brief?

**Comment by alpower** [comment]
thanks @robb0wen  - good spot - I'll have a look at that and update the PR 👍

**Comment by alpower** [comment]
OK @robb0wen I think I've made the necessary changes. Thanks!

**Comment by robb0wen** [comment]
Thanks @alpower. All good, I'll merge it in.

**Pull request merged**
